# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# website for config: https://github.com/mmistakes/so-simple-theme#configuring

title: Sivert Bakken's Website
email: sivert.bakken@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 A website to get in contact with me, and
 to see what I have been and am working on.
site.logo: /_images/sivert.jpg
skin: "/assets/css/skins/default.css"
date_format: "%Y-%m-%d"

logo: "/_images/sivert.png"



mathjax:
  enable: true             # MathJax equations, e.g. true, false (default)
  combo: "tex-svg"         # "tex-svg" (default), "tex-mml-chtml", etc.
  tags: "ams"              # "none", "ams" (default), "all"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

footer_links:
  - title: GitHub
    url: https://github.com/sivertba
    icon: fab fa-github-square
  - title: Facebook
    url: https://www.facebook.com/sivert.bakken/
    icon: fab fa-facebook
  - title: LinkedIn
    url: https://www.linkedin.com/in/sivert-bakken/
    icon: fab fa-linkedin
  - title: Mail
    url: mailto:sivert.bakken@gmail.com
    icon: fas fa-envelope-square

# theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll-theme-so-simple

include:
  - _images
  - _pdfs
  - _posts

# Site Author
author:
  name: Sivert Bakken


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
